window.onload=function(){
	var qianduankaifa=document.getElementById('qianduankaifa');
	var houduankaifa=document.getElementById('houduankaifa');
	var yidongkaifa=document.getElementById('yidongkaifa');
	var quanbu=document.getElementById('quanbu');
	var hh1=document.getElementById('hh1');
	var hh2=document.getElementById('hh2');
	var hh3=document.getElementById('hh3');
	var hh4=document.getElementById('hh4');
	var hh5=document.getElementById('hh5');
	var hh6=document.getElementById('hh6');
	quanbu.onmouseover=function(){
			document.image1.src="../../images/Android.png";
			document.image2.src="../../images/thinkPHP.png";
			document.image3.src="../../images/springsecurty.png";
			document.image4.src="../../images/Python2.png";
			document.image5.src="../../images/truedata.png";
			document.image6.src="../../images/BAT.png";
			hh1.innerHTML = "Android通用框架设计与完整的电商App开发";
			hh2.innerHTML = "ThinkPHP 5.0开发微信小程序商场打通全 栈项目架构";
			hh3.innerHTML = "Spring Security开发安全的REST服务操作系统";
			hh4.innerHTML = "全网热Python3入门+进阶 更快上手 实际开发";
			hh5.innerHTML = "对接真实数据 从0开发前后端分离企业级 上线项目";
			hh6.innerHTML = "BAT大咖助力 全面升级Android面试操作系统";
		}
	qianduankaifa.onmouseover=function(){
			document.image1.src="../../images/BAT.png";
			document.image2.src="../../images/JavaSpring.png";
			document.image3.src="../../images/springsecurty.png";
			document.image4.src="../../images/SSM.png";
			document.image5.src="../../images/thinkPHP.png";
			document.image6.src="../../images/ava.png";
			hh1.innerHTML = "BAT大咖助力 全面升级Android面试操作系统";
			hh2.innerHTML = "Java SpringBoot Spring Boot带前后端 企业级博客系统";
			hh3.innerHTML = "Spring Security开发安全的REST服务操作系统";
			hh4.innerHTML = "SSM到Spring Boot从零开发校园商铺平台系统";
			hh5.innerHTML = "ThinkPHP 5.0开发微信小程序商场打通全 栈项目架构";
			hh6.innerHTML = "编程小白入门 ava C++算法与数据结构精讲课程";
		
		}
	houduankaifa.onmouseover=function(){
		    document.image1.src="../../images/springsecurty.png";
			document.image2.src="../../images/SSM.png";
			document.image3.src="../../images/thinkPHP.png";
			document.image4.src="../../images/ava.png";
			document.image5.src="../../images/H5.png";
			document.image6.src="../../images/Android3.png";
			hh1.innerHTML = "Spring Security开发安全的REST服务操作系统";
			hh2.innerHTML = "SSM到Spring Boot从零开发校园商铺平台系统";
			hh3.innerHTML = "ThinkPHP 5.0开发微信小程序商场打通全 栈项目架构";
			hh4.innerHTML = "编程小白入门 ava C++算法与数据结构精讲课程";
			hh5.innerHTML = "编程小白入门 HTML5与CSS3实现动态网页项目开发";
			hh6.innerHTML = "课程进阶Android高级面试 10大开源框架 源码解析";
	}
	yidongkaifa.onmouseover=function(){
		    document.image1.src="../../images/BAT.png";
			document.image2.src="../../images/JavaSpring.png";
			document.image3.src="../../images/SSM.png";
			document.image4.src="../../images/thinkPHP.png";
			document.image5.src="../../images/ava.png";
			document.image6.src="../../images/truedata.png";
			hh1.innerHTML = "BAT大咖助力 全面升级Android面试操作系统";
			hh2.innerHTML = "Java SpringBoot Spring Boot带前后端 企业级博客系统";
			hh3.innerHTML = "SSM到Spring Boot从零开发校园商铺平台系统";
			hh4.innerHTML = "ThinkPHP 5.0开发微信小程序商场打通全 栈项目架构";
			hh5.innerHTML = "编程小白入门 ava C++算法与数据结构精讲课程";
			hh6.innerHTML = "编程小白入门C++远征之起航篇 项目入门必看";
	}	
}